apiVersion: apps/v1
kind: Deployment
metadata:
  name: sub-workflow-deployments
spec:
  selector:
    matchLabels:
      app: mosquitto
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mqtt-forward
        image: joeyw526/mqtt-forward:v1
      - name: face-detector
        image: joeyw526/face-detector:v1
        securityContent:
          priviledged: true
        volumeMounts:
        - mountPath: /dev/video0
          name: dev-video0
        volumes:
        - name: dev-video0
          hostPath:
            path: /dev/video0