apiVersion: apps/v1
kind: Deployment
metadata:
  name: save-images-deployment
spec:
  selector:
    matchLabels:
      app: mosquitto
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: save-images
        image: joeyw526/save-images:v1
        ports:
        - containerPort: 1883